<?php

declare(strict_types=1);

/*
 * Tests of the pure security-key core (WebAuthn second factor, D-128): php tests/security_key/run.php [filter]
 * (task test:security-key).
 *
 * Every *Test.php class in this directory; public methods named test*. Exit code 1 when a test fails or the filter
 * selects nothing. Keys are generated by the run; the EspoCRM side is covered by tests/security_key_stand.
 */

namespace Itvolga\Tests\SecurityKey;

use Itvolga\Tests\Finance\AssertionFailed;
use Itvolga\Tests\Finance\Skipped;

require __DIR__ . '/bootstrap.php';

// A warning or notice of the code under test fails the test.
set_error_handler(static function (int $severity, string $message, string $file, int $line): bool {
    throw new \ErrorException($message, 0, $severity, $file, $line);
});

$filter = $argv[1] ?? null;
$files = glob(__DIR__ . '/*Test.php') ?: [];
sort($files);
$passed = $failed = $skipped = 0;

foreach ($files as $file) {
    $class = __NAMESPACE__ . '\\' . basename($file, '.php');

    foreach (get_class_methods($class) as $method) {
        if (!str_starts_with($method, 'test') || ($filter !== null && !str_contains("$class::$method", $filter))) {
            continue;
        }

        $name = basename($file, '.php') . "::$method";

        try {
            $case = new $class();
            $case->setUp();
            $case->$method();
            $passed++;
            echo "  ok    $name\n";
        } catch (Skipped $e) {
            $skipped++;
            echo "  skip  $name — {$e->getMessage()}\n";
        } catch (\Throwable $e) {
            $failed++;
            $where = $e instanceof AssertionFailed ? '' : ' (' . $e::class . ' at ' . basename($e->getFile()) . ':' . $e->getLine() . ')';
            echo "  FAIL  $name — {$e->getMessage()}$where\n";
        }
    }
}

echo "---\nsecurity key tests: $passed passed, $failed failed, $skipped skipped\n";
exit($failed > 0 || $passed + $skipped === 0 ? 1 : 0);
