<?php

// Generated by tests/finance/build-source-profile.php from the private audit run 20260930T220947.
// Counts only (server-side aggregates) and HMAC digests of the monetary control sums; do not edit by hand.

return array (
  'run' => '20260930T220947',
  'documents' => 1078,
  'formulaClasses' => 
  array (
    'Act|group_tax_inc|noLineTax' => 21,
    'Act|individual|noLineTax' => 383,
    'Invoice|group_tax_inc|noLineTax' => 31,
    'Invoice|group_tax_inc|taxIncludedInPrice' => 1,
    'Invoice|group|groupTaxAdded' => 2,
    'Invoice|individual|lineTaxNotApplied' => 148,
    'Invoice|individual|noLineTax' => 454,
    'Quotes|individual|lineTaxNotApplied' => 23,
    'Quotes|individual|noLineTax' => 1,
    'SalesOrder|group_tax_inc|noLineTax' => 1,
    'SalesOrder|individual|lineTaxNotApplied' => 13,
  ),
  'allocationPartition' => 
  array (
    'both_same_invoice' => 425,
    'conflict_rel_other_invoice' => 38,
    'rel_only' => 56,
    'related_to_invoice_only' => 152,
    'related_to_salesorder' => 7,
    'unallocated' => 120,
  ),
  'outgoingLinkedToInvoices' => 52,
  'margins' => 
  array (
    'Act' => 
    array (
      'lines' => 417,
      'ok' => 417,
      'notComputed' => 0,
      'mismatch' => 0,
    ),
    'Invoice' => 
    array (
      'lines' => 712,
      'ok' => 486,
      'notComputed' => 226,
      'mismatch' => 0,
    ),
    'Quotes' => 
    array (
      'lines' => 27,
      'ok' => 1,
      'notComputed' => 26,
      'mismatch' => 0,
    ),
    'SalesOrder' => 
    array (
      'lines' => 14,
      'ok' => 1,
      'notComputed' => 13,
      'mismatch' => 0,
    ),
  ),
  'coverage' => 
  array (
    'Invoice|' => 
    array (
      'n' => 4,
      'none' => 3,
      'one' => 1,
      'many' => 0,
      'paid' => 1,
      'partial' => 0,
      'overpaid' => 0,
    ),
    'Invoice|Approved' => 
    array (
      'n' => 5,
      'none' => 4,
      'one' => 1,
      'many' => 0,
      'paid' => 1,
      'partial' => 0,
      'overpaid' => 0,
    ),
    'Invoice|Cancel' => 
    array (
      'n' => 17,
      'none' => 17,
      'one' => 0,
      'many' => 0,
      'paid' => 0,
      'partial' => 0,
      'overpaid' => 0,
    ),
    'Invoice|Created' => 
    array (
      'n' => 34,
      'none' => 25,
      'one' => 8,
      'many' => 1,
      'paid' => 6,
      'partial' => 3,
      'overpaid' => 0,
    ),
    'Invoice|Credit Invoice' => 
    array (
      'n' => 6,
      'none' => 6,
      'one' => 0,
      'many' => 0,
      'paid' => 0,
      'partial' => 0,
      'overpaid' => 0,
    ),
    'Invoice|Paid' => 
    array (
      'n' => 561,
      'none' => 36,
      'one' => 468,
      'many' => 57,
      'paid' => 473,
      'partial' => 17,
      'overpaid' => 35,
    ),
    'Invoice|Sent' => 
    array (
      'n' => 9,
      'none' => 6,
      'one' => 2,
      'many' => 1,
      'paid' => 1,
      'partial' => 2,
      'overpaid' => 0,
    ),
    'SalesOrder|Created' => 
    array (
      'n' => 1,
      'none' => 1,
      'one' => 0,
      'many' => 0,
      'paid' => 0,
      'partial' => 0,
      'overpaid' => 0,
    ),
    'SalesOrder|Одобрено' => 
    array (
      'n' => 9,
      'none' => 7,
      'one' => 0,
      'many' => 2,
      'paid' => 0,
      'partial' => 2,
      'overpaid' => 0,
    ),
    'SalesOrder|Создано' => 
    array (
      'n' => 4,
      'none' => 3,
      'one' => 1,
      'many' => 0,
      'paid' => 1,
      'partial' => 0,
      'overpaid' => 0,
    ),
  ),
  'legalEntityValues' => 
  array (
    'Act|Default' => 402,
    'Act|По умолчанию' => 2,
    'Invoice|Default' => 548,
    'Invoice|По умолчанию' => 88,
    'Quotes|Default' => 22,
    'Quotes|По умолчанию' => 2,
    'SPPayments|(empty)' => 188,
    'SPPayments|Default' => 473,
    'SPPayments|По умолчанию' => 137,
    'SalesOrder|Default' => 13,
    'SalesOrder|По умолчанию' => 1,
  ),
  'controlSumDigests' => 
  array (
    'doc_sums' => 
    array (
      'rows' => 44,
      'hmac' => '74838e7a01864fb02a701b2fbe026fc5abbda2f36fabd7577979b119be6077d2',
    ),
    'line_sums' => 
    array (
      'rows' => 4,
      'hmac' => '19f8ad7119b18efa06c61ffc43d7538b6333b6bf7aa42d85334401d3bfb977f1',
    ),
    'payment_sums' => 
    array (
      'rows' => 25,
      'hmac' => '83081409e19ded0802b835e68420c2966923b83333370ebba25e547404f48705',
    ),
    'alloc_sums' => 
    array (
      'rows' => 10,
      'hmac' => 'b97c0b694a0d18275f71c8e28901230378810be26639861df63a91786c96fdf5',
    ),
    'coverage_sums' => 
    array (
      'rows' => 10,
      'hmac' => '3c06e557e08e10beb612d0ffcb7d54a6cb8f3b8f338df5fab61890a79e1b12d3',
    ),
  ),
);
