#!/usr/bin/env python3
"""Coverage of every finance field and link of the source audit (stage 04.6) → docs/migration/finance-coverage.md.

Usage: build_finance_coverage.py [--check] [REPO]
  without --check: writes the document when it changed; --check: writes nothing, exit 1 when it would change.
  Both exit 1 when a row is open (no final disposition) — every finance row of the audit must be implemented or decided.

Inputs are public: docs/migration/field-map.csv and relations.csv (generated by scripts/audit/build_maps.py from a
private audit run; only schema, counts and the mapping) and the merged EspoCRM metadata (scripts/model/model_check.py).
Every row of the finance scope gets one disposition from a closed set; an implemented row must pass the model check
now, with the stage and the check text stored in the map (otherwise the maps are stale: rerun build_maps.py). The
registry of finance documents (app.itvolgaFinance) is checked against the model as the document chain.
"""
import csv
import re
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import model_check as MC  # noqa: E402

OUT = "docs/migration/finance-coverage.md"

# Source modules of the finance scope, in document order: module → section title.
MODULES = {
    "Quotes": "Предложения (Quotes → Quote)",
    "SalesOrder": "Заказы (SalesOrder)",
    "Invoice": "Счета (Invoice)",
    "Act": "Акты (Act)",
    "SPPayments": "Платежи (SPPayments → Payment)",
    "PurchaseOrder": "Заказы поставщикам (PurchaseOrder): записей нет, сущность не создаётся",
    "Consignment": "Накладные (Consignment → VtigerArchive, только чтение)",
    "VTEItems": "Строки VTEItems: дубль строк документов, исключены (D-09)",
}
# Columns of other modules that point at a finance record.
REFERENCES = {"invoiceid", "salesorderid", "salesorder_id", "quoteid", "quote_id", "sp_act_id", "purchaseorderid"}
REFERENCE_SECTION = "Ссылки других модулей на финансовые документы"
# Rows without a module (physical columns of tables): section title → table pattern.
TABLE_SECTIONS = {
    "Таблицы документов (ключи, адреса, пользовательские поля)":
        r"^vtiger_(quotes|salesorder|invoice|sp_act|sp_consignment|purchaseorder|vteitems)(cf|billads|shipads)?$"
        r"|^vtiger_(sobillads|soshipads|pobillads|poshipads|invoice_recurring_info)$",
    "Строки документов": r"^vtiger_inventory(productrel|chargesrel)(_seq)?$",
    "Таблицы платежей": r"^sp_payments",
    "Юрлицо": r"^vtiger_(organizationdetails|spcompany)(_seq)?$",
    "Налоги, валюта, доп. расходы":
        r"^vtiger_(inventorytaxinfo|shippingtaxinfo|inventorycharges|taxclass|currency_info|currencies|"
        r"productcurrencyrel)(_seq)?$",
    "Справочники статусов и значений":
        r"^vtiger_(quotestage|sostatus|invoicestatus|sp_actstatus|postatus|sp_consignmentstatus|spstatus|pay_type|"
        r"type_payment|carrier|recurring_frequency|payment_duration)(_seq)?$",
    "История статусов": r"^vtiger_(invoicestatushistory|sp_actstatushistory)(_seq)?$",
    "Нумерация": r"^vtiger_modentity_num(_seq)?$",
    "Печатные формы, условия, уведомления":
        r"^(sp_templates|vtiger_quotingtool\w*|vtiger_inventory_tandc|vtiger_inventorynotification)(_seq)?$",
    "Настройки платного расширения Quoter": r"^quoter_",
}
# Tables that look financial but are not: why they stay out of the scope.
OUT_OF_SCOPE = {
    r"^vtiger_(currency_decimal_separator|currency_grouping_pattern|currency_grouping_separator|"
    r"currency_symbol_placement|no_of_currency_decimals)(_seq)?$": "формат чисел пользователя (Preferences, этап 03)",
    r"^vtiger_emailtemplates(_seq)?$": "шаблоны писем, не финансовые печатные формы",
    r"^vtiger_glacct(_seq)?$": "счёт учёта товара (Products, этап 03)",
    r"^vtiger_recurringtype(_seq)?$": "повторение событий календаря (Events, этап 03), не периодичность заказов",
}
# Every module-less table matching this must be in a section or out of the scope (nothing is dropped silently).
FINANCE_LOOKING = re.compile(r"quot|salesorder|invoice|sp_act|payment|pay_type|inventory|tax|currenc|charges|spcompany|"
                             r"organization|modentity|templat|consign|purchaseorder|vteitem|carrier|recurring|glacct|"
                             r"^vtiger_(so|po)(bill|ship)ads")
# Shared record columns that carry the identity of every imported finance record.
SHARED = {("vtiger_crmentity", "crmid"), ("vtiger_crmentity", "setype")}
SHARED_SECTION = "Общие колонки записей (vtiger_crmentity)"

# Dispositions, in the order of the summary columns.
KINDS = ["перенос", "рабочее поле, в источнике пусто", "справочник", "архив", "ключ", "настройка", "печатная форма",
         "исключено", "пусто", "открыто"]
KIND_NOTES = {
    "перенос": "значения переносятся в рабочее поле EspoCRM (поле или связь есть в модели, проверено `model_check`)",
    "рабочее поле, в источнике пусто": "в источнике значений нет; поле нужно новым документам (D-47) и есть в модели",
    "справочник": "значения — опции enum и словарь `vtigerValueMap` (D-38)",
    "архив": "исходные значения хранятся только для чтения (`vtigerData`, `VtigerArchive.data`)",
    "ключ": "ключ записи или соединения таблиц: исходный id → `vtigerId`, тип записи → целевая сущность",
    "настройка": "воспроизводится настройкой EspoCRM (валюта RUB, без НДС — D-21, D-37; условия документов по умолчанию — "
                 "D-83)",
    "печатная форма": "шаблон источника воспроизведён печатной формой модуля (этап 05, D-79; реестр и файлы форм "
                      "проверены `model_check`)",
    "исключено": "не переносится по решению (причина — в строке)",
    "пусто": "в источнике значений нет, рабочее поле не создаётся",
    "открыто": "нет окончательного решения — должно быть 0",
}
# Acceptance tests of each finance entity (tests/stage04, synthetic data on the stand; the core: tests/finance).
ENTITY_TESTS = {
    "Quote, QuoteItem": ["tests/stage04/test_stage04_2.py", "tests/stage04/test_stage04_6.py"],
    "SalesOrder, SalesOrderItem": ["tests/stage04/test_stage04_2.py", "tests/stage04/test_stage04_6.py"],
    "Invoice, InvoiceItem": ["tests/stage04/test_stage04_3.py", "tests/stage04/test_stage04_6.py"],
    "Payment, PaymentAllocation": ["tests/stage04/test_stage04_4.py", "tests/stage04/test_stage04_6.py"],
    "Act, ActItem": ["tests/stage04/test_stage04_5.py", "tests/stage04/test_stage04_6.py"],
    "LegalEntity": ["tests/stage04/test_stage04_2.py", "tests/stage04/test_stage04_3.py"],
    "расчётное ядро (итоги, налоги, оплата, юрлицо)": ["tests/finance/run.php"],
    "печатные формы (этап 05)": ["tests/stage05/test_stage05.py", "tests/finance/run.php"],
}


def read_csv(repo, name):
    with open(repo / "docs/migration" / name, encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def field_section(row):
    module, table, column = row["source_module"], row["source_table"], row["source_column"]
    if module in MODULES:
        return MODULES[module]
    if module:
        return REFERENCE_SECTION if column in REFERENCES or row["source_field"] in REFERENCES else None
    if (table, column) in SHARED:
        return SHARED_SECTION
    found = [title for title, rx in TABLE_SECTIONS.items() if re.search(rx, table)]
    if len(found) > 1:
        raise SystemExit(f"{table}: matches sections {found}")
    return found[0] if found else None


def relation_section(row):
    modules = row["from_module"].split("|") + row["to_module"].split("|")
    for module in modules:
        if module in MODULES:
            return MODULES[module]
    if row["source_object"].rsplit(".", 1)[-1] in REFERENCES:
        return REFERENCE_SECTION
    return None


def unscoped_tables(fields):
    """Module-less tables that look financial but are neither in a section nor declared out of the scope."""
    tables = {r["source_table"] for r in fields if not r["source_module"]}
    missing = []
    for table in sorted(tables):
        if not FINANCE_LOOKING.search(table):
            continue
        in_section = any(re.search(rx, table) for rx in TABLE_SECTIONS.values())
        if not in_section and not any(re.search(rx, table) for rx in OUT_OF_SCOPE):
            missing.append(table)
    return missing


def disposition(row, status, fate, target, res, text, stage):
    """(kind, reason) of one row; `open` when it has no final decision or the map is stale."""
    if res is False:
        return "открыто", f"ошибка модели: {text}"
    if status.startswith("реализовано"):
        if res is not True:
            return "открыто", f"отмечено реализованным, проверка модели: {text}"
        if status != f"реализовано (этап {stage})" or row["espo_check"] != text:
            return "открыто", "карта устарела: перегенерировать build_maps.py"
        if target == MC.PRINT_FORMS_TARGET:
            return "печатная форма", text
        if target == MC.TERMS_TARGET:
            return "настройка", text
        if fate.startswith("архив"):
            return "архив", text
        if fate.startswith("пусто"):
            return "рабочее поле, в источнике пусто", text
        return ("справочник" if target == "entityDefs options" else "перенос"), text
    if res is True:
        return "открыто", "цель есть в модели, а статус карты — нет: перегенерировать build_maps.py"
    if status.startswith("контракт") or status == "не проверено":
        return "открыто", f"статус «{status}»: {fate}"
    if target in ("(ключ записи)", "(тип сущности)") or fate.startswith("только ключ записи"):
        return "ключ", text if text != "—" else fate
    if target == "entityDefs options":
        # A dictionary without enum options is decided only by an explicit fate (model_check.PICKLIST_FATE); the
        # generic fallback of model_check would hide a missing value map.
        explicit = MC.PICKLIST_FATE.get(row["source_table"].removeprefix("vtiger_"))
        if explicit is None:
            return "открыто", f"справочник без опций enum и без решения: {text}"
        return ("архив" if explicit.startswith("архив") else "исключено"), explicit
    if target == "config":
        return "настройка", fate
    if fate.startswith(("исключено", "не переносится")):
        return "исключено", re.sub(r"^(исключено:\s*)+", "", fate)
    if fate.startswith("пусто"):
        return "пусто", fate
    return "открыто", f"«{fate}» без проверенной цели"


def cell(value):
    return str(value).replace("\n", " ").replace("|", "\\|").replace("<", "&lt;").strip() or "—"


def count_cell(row):
    if row.get("live_records"):
        return f"{row['nonempty_live'] or 0} из {row['live_records']}"
    return f"всего {row.get('nonempty_all_rows') or 0}"


def target_cell(row):
    entity = re.sub(r"\s*\(собственная\)$", "", row["target_entity"])
    field = row["target_field"]
    if field in ("", "—"):
        return "—"
    if entity in ("", "—", "?") or "." in field or field.startswith("(") or " " in entity:
        return field
    return f"{entity}.{field}"


# The chain of the finance contract (finance-contract.md §18.2): every step must be in the registry and in the model.
CHAIN_DOCUMENTS = ["Quote", "SalesOrder", "Invoice", "Act"]
CHAIN_CONVERSIONS = [("Quote", "SalesOrder"), ("Quote", "Invoice"), ("SalesOrder", "Invoice"), ("Invoice", "Act")]
CHAIN_PAYMENTS = {"Payment": ["Invoice", "SalesOrder"]}


def reciprocal(model, entity, link, other):
    """entity.link points at `other` and the foreign link of `other` points back at entity.link (both sides)."""
    defs = model.link(entity, link) or {}
    back = model.link(other, defs.get("foreign") or "") or {}
    return defs.get("entity") == other and back.get("entity") == entity and back.get("foreign") == link


def dictionary_problems(model, table):
    """A dictionary is covered only by a value map whose every target value is an option of its enum (D-38)."""
    picklist = table.removeprefix("vtiger_")
    problems = []
    for entity, data in sorted(model.value_maps.items()):
        for field, spec in data.get("fields", {}).items():
            if picklist not in spec.get("picklists", []):
                continue
            options = model.options(entity, field)
            keys = [key for mapping in spec.get("map", {}).values() for key in mapping.values()]
            if not options or not keys or any(key not in options for key in keys):
                problems.append(f"{entity}.{field}: словарь пуст или не сходится с опциями enum")
    return problems


def chain_checks(model, registry=None):
    """The finance registry (documents, conversions, payment targets) against the contract chain and the model:
    (rows, problems). A step missing from the registry or a link without its reciprocal is a problem."""
    if registry is None:
        registry = model.load("app").get("itvolgaFinance", {})
    documents, conversions = registry.get("documents", {}), registry.get("conversions", {})
    payments = registry.get("payments", {})
    rows, problems = [], []
    problems += [f"реестр: нет документа {doc}" for doc in CHAIN_DOCUMENTS if doc not in documents]
    problems += [f"реестр: нет конвертации {src} → {dst}" for src, dst in CHAIN_CONVERSIONS
                 if dst not in conversions.get(src, {})]
    problems += [f"реестр: нет распределения {payment} → {doc}" for payment, docs in CHAIN_PAYMENTS.items()
                 for doc in docs if doc not in payments.get(payment, {}).get("targets", {})]
    for doc, defs in documents.items():
        item, parent = defs["itemEntityType"], defs["parentLink"]
        ok = reciprocal(model, doc, "items", item) and (model.link(doc, "items") or {}).get("foreign") == parent
        rows.append((f"{doc} → позиции", f"{doc}.items ↔ {item}.{parent}", "—", "ok" if ok else "ОШИБКА"))
        if not ok:
            problems.append(f"позиции {doc}: нет взаимной связи {doc}.items ↔ {item}.{parent}")
    for src, targets in conversions.items():
        for dst, conversion in targets.items():
            link = conversion["link"]
            missing = [f for f in conversion["fieldList"] if not (model.field(src, f) and model.field(dst, f))]
            ok = reciprocal(model, dst, link, src) and not missing
            how = "ключ у источника" if (model.link(dst, link) or {}).get("type") == "hasMany" else "ссылка у нового документа"
            rows.append((f"{src} → {dst}", f"{dst}.{link} ({how})", ", ".join(conversion["fieldList"]),
                         "ok" if ok else "ОШИБКА: " + ", ".join(missing or ["связь"])))
            if not ok:
                problems.append(f"конвертация {src} → {dst}: связь или поля {missing}")
    for payment, defs in payments.items():
        allocation = defs["allocationEntityType"]
        for doc, link in defs["targets"].items():
            ok = reciprocal(model, allocation, link, doc)
            rows.append((f"{payment} → {doc}", f"{allocation}.{link} ↔ {doc}.paymentAllocations",
                         "«Добавить платёж»: плательщик, сумма, строка распределения", "ok" if ok else "ОШИБКА"))
            if not ok:
                problems.append(f"распределение {payment} → {doc}: нет взаимной связи {allocation}.{link}")
    return rows, problems


def build(repo):
    model = MC.Model(repo)
    fields, relations = read_csv(repo, "field-map.csv"), read_csv(repo, "relations.csv")
    open_rows = [f"таблица `{t}` похожа на финансовую, но не входит ни в раздел, ни в исключения области"
                 for t in unscoped_tables(fields)]

    sections, summary, dates = {}, {}, Counter()
    for row in fields:
        section = field_section(row)
        if section is None:
            continue
        res, text = MC.check_field_row(model, row, row.get("max_len_live") or None)
        stage = MC.implemented_stage(model, row) if res is True else None
        kind, reason = disposition(row, row["mapping_status"], row["fate"], row["target_field"].strip(), res, text,
                                   stage)
        if kind == "справочник" and (problems := dictionary_problems(model, row["source_table"])):
            kind, reason = "открыто", "; ".join(problems)
        sections.setdefault(("field", section), []).append((row, kind, reason))
        summary.setdefault(section, Counter())[kind] += 1
        dates[row["count_status"]] += 1
        if kind == "открыто":
            open_rows.append(f"{row['source_table']}.{row['source_column']} ({row['source_module'] or 'без модуля'}): "
                             f"{reason}")
    for row in relations:
        section = relation_section(row)
        if section is None:
            continue
        res, text = MC.check_relation_row(model, row)
        stage = MC.implemented_stage(model, row) if res is True else None
        kind, reason = disposition(row, row["status"], row["fate"], row["target_link"].strip(), res, text, stage)
        sections.setdefault(("relation", section), []).append((row, kind, reason))
        summary.setdefault("Связи (relations.csv)", Counter())[kind] += 1
        if kind == "открыто":
            open_rows.append(f"связь {row['relation_id']}: {reason}")

    order = [*MODULES.values(), REFERENCE_SECTION, *TABLE_SECTIONS, SHARED_SECTION]
    sections = dict(sorted(sections.items(), key=lambda item: (item[0][0] == "relation", order.index(item[0][1]))))
    summary = dict(sorted(summary.items(), key=lambda item: order.index(item[0]) if item[0] in order else len(order)))
    chain, problems = chain_checks(model)
    open_rows += problems
    missing_tests = sorted({p for paths in ENTITY_TESTS.values() for p in paths if not (repo / p).exists()})
    open_rows += [f"нет файла тестов {p}" for p in missing_tests]
    return render(sections, summary, dates, chain, open_rows), open_rows, summary


def render(sections, summary, dates, chain, open_rows):
    audit = ", ".join(sorted(dates)) or "—"
    out = [
        "# Покрытие финансовых полей и связей аудита (этап 04.6)",
        "",
        "<!-- Сгенерировано scripts/model/build_finance_coverage.py — не править вручную; проверка: task model:check. -->",
        "",
        f"Источник — `field-map.csv` и `relations.csv` (счётчики аудита: {audit}) и модель EspoCRM (метаданные ядра и "
        "модуля `Itvolga`). Каждая строка области получает один итог; реализованная строка заново проверяется "
        "`model_check` (стадия и текст проверки должны совпасть с картой). Покрытие строки — модель и путь записи; "
        "сверка значений живых записей после импорта — этап 06.4.",
        "",
        "## Область",
        "",
        "- Модули: " + ", ".join(f"`{m}`" for m in MODULES) + ".",
        "- Ссылки других модулей на финансовые документы: колонки " + ", ".join(f"`{c}`" for c in sorted(REFERENCES)) + ".",
        "- Таблицы без модуля: " + "; ".join(f"{title} (`{rx}`)" for title, rx in TABLE_SECTIONS.items()) + ".",
        "- Общие колонки записей: " + ", ".join(f"`{t}.{c}`" for t, c in sorted(SHARED)) + ".",
        "- Вне области (похожи на финансовые): " + "; ".join(f"`{rx}` — {why}" for rx, why in OUT_OF_SCOPE.items()) + ".",
        "",
        "## Итоги",
        "",
        "| Раздел | " + " | ".join(KINDS) + " | всего |",
        "|---|" + "---:|" * (len(KINDS) + 1),
    ]
    total = Counter()
    for section, counts in summary.items():
        total.update(counts)
        out.append(f"| {cell(section)} | " + " | ".join(str(counts.get(k, 0) or "") for k in KINDS)
                   + f" | {sum(counts.values())} |")
    out.append("| **всего** | " + " | ".join(f"**{total.get(k, 0)}**" for k in KINDS) + f" | **{sum(total.values())}** |")
    out += ["", "Итоги:", ""]
    out += [f"- **{k}** — {KIND_NOTES[k]}." for k in KINDS]
    out += ["", "## Открытые расхождения", ""]
    out += [f"- {cell(x)}" for x in open_rows] if open_rows else ["Нет: у каждой строки области есть окончательный итог."]
    out += ["", "## Цепочка документов (реестр `app.itvolgaFinance`)", "",
            "| Переход | Связь | Копируемые поля | Модель |", "|---|---|---|---|"]
    out += [f"| {cell(a)} | {cell(b)} | {cell(c)} | {cell(d)} |" for a, b, c, d in chain]
    out += ["", "Статус, номер, даты, итоги и пометки источника не копируются: у нового документа — свои умолчания, "
            "номер из счётчика и расчёт ядра; юрлицо подставляет сервер; платёж назначается текущему пользователю (D-67).",
            "", "## Тесты по сущностям", "", "| Сущность | Тесты |", "|---|---|"]
    out += [f"| {cell(entity)} | " + ", ".join(f"`{p}`" for p in paths) + " |" for entity, paths in ENTITY_TESTS.items()]
    for (kind, section), rows in sections.items():
        if kind == "field":
            out += ["", f"## Поля: {section}", "",
                    "| Колонка | Поле Vtiger | Непустых | Цель | Итог | Статус карты | Причина / проверка |",
                    "|---|---|---:|---|---|---|---|"]
            for row, disp, reason in rows:
                label = row["source_field"] + (f" ({row['source_label']})" if row["source_label"] else "")
                out.append(f"| `{cell(row['source_table'] + '.' + row['source_column'])}` | {cell(label)} | "
                           f"{cell(count_cell(row))} | {cell(target_cell(row))} | {disp} | {cell(row['mapping_status'])} | "
                           f"{cell(reason)} |")
        else:
            out += ["", f"## Связи: {section}", "",
                    "| Связь | Вид | Откуда → куда | Живых | Цель | Итог | Статус карты | Причина / проверка |",
                    "|---|---|---|---:|---|---|---|---|"]
            for row, disp, reason in rows:
                out.append(f"| `{cell(row['relation_id'])}` | {cell(row['kind'])} | "
                           f"{cell(row['from_module'] + ' → ' + row['to_module'])} | {cell(row['live_count'])} | "
                           f"{cell(row['target_link'])} | {disp} | {cell(row['status'])} | {cell(reason)} |")
    return "\n".join(out) + "\n"


def main():
    args = [a for a in sys.argv[1:] if a != "--check"]
    check = "--check" in sys.argv[1:]
    repo = Path(args[0]) if args else MC.REPO
    text, open_rows, summary = build(repo)
    path = repo / OUT
    changed = not path.exists() or path.read_text(encoding="utf-8") != text
    fields = sum(sum(c.values()) for s, c in summary.items() if s != "Связи (relations.csv)")
    links = sum(summary.get("Связи (relations.csv)", Counter()).values())
    print(f"{OUT}: {fields} fields, {links} relations, open {len(open_rows)}"
          + (" — would change" if check and changed else ""))
    for line in open_rows:
        print(f"  open: {line}")
    if changed and not check:
        path.write_text(text, encoding="utf-8")
    sys.exit(1 if open_rows or (check and changed) else 0)


if __name__ == "__main__":
    main()
