<?php

declare(strict_types=1);

/*
 * Builds tests/finance/fixtures/source-profile.php — the anonymised profile of the source that SourceSnapshotTest
 * compares the finance core with:
 *
 *   php tests/finance/build-source-profile.php /data/itvolga/espo-private/audit/<run>
 *
 * Counts come from the server-side aggregates of the same audit run (34_finance_config, 33_allocation_check,
 * 46_finance_contract) — computed by MySQL, independently of the core. Monetary control sums
 * (35_control_sums_private) are committed only as HMAC-SHA256 digests; the key is generated once in
 * /data/itvolga/espo-private/finance/control-digest.key (600) and never leaves the private directory.
 */

namespace Itvolga\Tests\Finance;

use Itvolga\Tests\Finance\Support\ControlSums;
use Itvolga\Tests\Finance\Support\PrivateTsv;

require __DIR__ . '/bootstrap.php';

$dir = rtrim($argv[1] ?? '', '/');

if ($dir === '' || !is_dir($dir)) {
    fwrite(STDERR, "usage: php tests/finance/build-source-profile.php <private audit run directory>\n");
    exit(2);
}

$keyFile = getenv('ITVOLGA_DIGEST_KEY') ?: '/data/itvolga/espo-private/finance/control-digest.key';

if (!is_file($keyFile)) {
    @mkdir(dirname($keyFile), 0700, true);
    file_put_contents($keyFile, bin2hex(random_bytes(32)) . "\n");
    chmod($keyFile, 0600);
}

$key = trim((string) file_get_contents($keyFile));
$config = PrivateTsv::read("$dir/34_finance_config.tsv");
$allocation = PrivateTsv::read("$dir/33_allocation_check.tsv");
$contract = PrivateTsv::read("$dir/46_finance_contract.tsv");
$int = static fn (string $v): int => $v === 'NULL' ? 0 : (int) $v;

// Formula classes as MySQL sees them (subtotal against Σ net and the line tax), translated to FormulaClass values.
$classes = [];

foreach ($config['formula_class'] as $r) {
    $class = match ($r['cls']) {
        'sub=net(no tax)' => 'noLineTax',
        'sub=net(tax on lines ignored)' => match ($r['taxtype']) {
            'individual' => 'lineTaxNotApplied',
            'group_tax_inc' => 'taxIncludedInPrice',
            'group' => 'groupTaxAdded',
        },
        default => 'unverified',
    };
    $classes["{$r['setype']}|{$r['taxtype']}|$class"] = $int($r['n']);
}

$partition = [];

foreach ($allocation['alloc_partition'] as $r) {
    $partition[$r['category']] = $int($r['payments']);
}

$margins = [];

foreach ($contract['line_shape'] as $r) {
    $margins[$r['m']] = [
        'lines' => $int($r['n']),
        'ok' => $int($r['margin_eq_net_minus_cost']),
        'notComputed' => $int($r['margin_zero_net_nz']),
        'mismatch' => $int($r['margin_other']),
    ];
}

$coverage = [];

foreach ($contract['coverage_d11'] as $r) {
    $st = $r['st'] === '(null)' ? '' : $r['st'];
    $coverage["{$r['m']}|$st"] = [
        'n' => $int($r['n']), 'none' => $int($r['no_payment']), 'one' => $int($r['one_payment']), 'many' => $int($r['many_payments']),
        'paid' => $int($r['paid_eq_total']), 'partial' => $int($r['partial']), 'overpaid' => $int($r['overpaid']),
    ];
}

$legalEntity = [];

foreach ($contract['spcompany_usage'] as $r) {
    if (in_array($r['m'], [...ControlSums::DOCUMENT_MODULES, 'SPPayments'], true)) {
        $legalEntity["{$r['m']}|{$r['val']}"] = ($legalEntity["{$r['m']}|{$r['val']}"] ?? 0) + $int($r['n']);
    }
}

$outgoingLinked = 0;

foreach ($contract['payment_shape'] as $r) {
    if ($r['pay_type'] === 'Expense') {
        $outgoingLinked += $int($r['with_rel']);
    }
}

$sums = ControlSums::fromServer("$dir/35_control_sums_private.tsv");
$digests = [];

foreach ($sums as $group => $rows) {
    $digests[$group] = ['rows' => count($rows), 'hmac' => ControlSums::digest($key, $group, $rows)];
}

foreach ([&$classes, &$partition, &$margins, &$coverage, &$legalEntity] as &$section) {
    ksort($section);
}

unset($section);

$profile = [
    'run' => basename($dir),
    'documents' => array_sum($classes),
    'formulaClasses' => $classes,
    'allocationPartition' => $partition,
    'outgoingLinkedToInvoices' => $outgoingLinked,
    'margins' => $margins,
    'coverage' => $coverage,
    'legalEntityValues' => $legalEntity,
    'controlSumDigests' => $digests,
];

$out = __DIR__ . '/fixtures/source-profile.php';
file_put_contents($out, "<?php\n\n// Generated by tests/finance/build-source-profile.php from the private audit run {$profile['run']}.\n"
    . "// Counts only (server-side aggregates) and HMAC digests of the monetary control sums; do not edit by hand.\n\n"
    . 'return ' . var_export($profile, true) . ";\n");
echo "profile: {$profile['documents']} documents, " . array_sum($partition) . " payments, "
    . count($digests) . " digest groups → " . substr($out, strlen(ITVOLGA_REPO) + 1) . "\n";
