#!/usr/bin/env bash
# Idempotent installer of the local EspoCRM stand (stage 02), without Docker.
#
#   scripts/stand/install.sh            # all steps, then the health check
#   scripts/stand/install.sh core perms # selected steps only
#
# Steps: preflight private user core perms mysql fpm espo apache cron health.
# Run as the developer (not root); privileged actions use `sudo -n`. Re-running is safe:
# files are rewritten only when their rendered content changes, services are restarted only then.
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

ALL_STEPS=(preflight private user core perms mysql fpm espo apache cron health)
CORE_STAMP="$ESPO_ROOT/.espocrm-core"   # "<version> <zip sha256>" + list of core top-level entries
REQUIRED_PHP_EXT=(bcmath ctype curl dom exif gd iconv json mbstring openssl pdo_mysql xml xmlwriter zip)
REQUIRED_CLI_EXT=(pcntl posix)          # parallel job processing in cron.php

step_preflight() {
    [[ $EUID -ne 0 ]] || die "run as the developer user, not root (sudo is used internally)"
    sudo -n true 2>/dev/null || die "passwordless sudo is required for the privileged steps"
    local cmd missing=()
    for cmd in curl unzip rsync xz tar python3 setfacl getfacl systemctl apache2ctl a2enmod a2ensite \
               logger ldconfig "$PHP_BIN" "$PHP_FPM_BIN"; do
        command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
    done
    [[ ${#missing[@]} -eq 0 ]] || die "missing commands: ${missing[*]} (see docs/local-stand.md, «Требования»)"
    local ext cli_mods fpm_mods
    cli_mods="$("$PHP_BIN" -m | tr '[:upper:]' '[:lower:]')"
    fpm_mods="$("$PHP_FPM_BIN" -m 2>/dev/null | tr '[:upper:]' '[:lower:]')"
    for ext in "${REQUIRED_PHP_EXT[@]}"; do
        grep -qx "$ext" <<<"$cli_mods" || missing+=("cli:$ext")
        grep -qx "$ext" <<<"$fpm_mods" || missing+=("fpm:$ext")
    done
    for ext in "${REQUIRED_CLI_EXT[@]}"; do
        grep -qx "$ext" <<<"$cli_mods" || missing+=("cli:$ext")
    done
    [[ ${#missing[@]} -eq 0 ]] || die "missing PHP $PHP_VERSION extensions: ${missing[*]}"
    local php_ver
    php_ver="$("$PHP_BIN" -r 'echo PHP_VERSION;')"
    "$PHP_BIN" -r 'exit(version_compare(PHP_VERSION, "8.3.0", ">=") && version_compare(PHP_VERSION, "8.6.0", "<") ? 0 : 1);' \
        || die "EspoCRM $ESPO_VERSION needs PHP >=8.3 <8.6, found $php_ver"
    local glibc
    glibc="$(getconf GNU_LIBC_VERSION | awk '{print $2}')"
    [[ "$(printf '%s\n2.28\n' "$glibc" | sort -V | head -n1)" == 2.28 ]] || die "glibc $glibc < 2.28 (MySQL generic build)"
    systemctl list-unit-files cron.service >/dev/null 2>&1 || die "cron.service not found"
    log "preflight ok: PHP $php_ver, glibc $glibc"
}

step_private() {
    install -d -m 0700 "$STAND_PRIVATE_DIR" "$BACKUP_DIR"
    if [[ ! -f "$STAND_PRIVATE_ENV" ]]; then
        ( umask 077
          { echo "# Generated by scripts/stand/install.sh on $(date -Is). Private: never commit."
            echo "DB_PASSWORD=$(random_secret 32)"
            echo "ESPO_ADMIN_USERNAME=admin"
            echo "ESPO_ADMIN_PASSWORD=$(random_secret 24)"
          } >"$STAND_PRIVATE_ENV" )
        log "generated $STAND_PRIVATE_ENV (mode 600)"
    fi
    chmod 600 "$STAND_PRIVATE_ENV"
    load_private_env
    [[ "$DB_PASSWORD" =~ ^[A-Za-z0-9]{16,}$ ]] || die "DB_PASSWORD must be 16+ alphanumeric characters"
}

step_user() {
    if ! id -u "$ESPO_USER" >/dev/null 2>&1; then
        as_root useradd --system --user-group --home-dir /nonexistent --no-create-home \
            --shell /usr/sbin/nologin --comment "EspoCRM local stand" "$ESPO_USER"
        log "created system user $ESPO_USER"
    fi
    # `php` shim for cron/CLI PATH (see STAND_PATH in deploy/local/stand.conf).
    as_root install -d -m 0755 "$STAND_BIN_DIR"
    as_root ln -sfn "$PHP_BIN" "$STAND_BIN_DIR/php"
    if ! id -u mysql >/dev/null 2>&1; then
        as_root useradd --system --user-group --home-dir /nonexistent --no-create-home \
            --shell /usr/sbin/nologin --comment "MySQL Server" mysql
        log "created system user mysql"
    fi
}

core_entries() { # list core top-level entries recorded in the stamp
    [[ -f "$CORE_STAMP" ]] && tail -n +2 "$CORE_STAMP"
}

step_core() {
    local zip want
    zip="$(fetch_verified "$ESPO_ZIP_URL" "$ESPO_ZIP" "$ESPO_ZIP_SHA256")"
    want="$ESPO_VERSION $ESPO_ZIP_SHA256"
    if [[ -f "$CORE_STAMP" ]]; then
        local have
        have="$(head -n1 "$CORE_STAMP")"
        if [[ "$have" == "$want" && -f "$ESPO_ROOT/application/Espo/Core/Application.php" && "${FORCE_CORE:-0}" != 1 ]]; then
            log "EspoCRM core $ESPO_VERSION already in place"
            return
        fi
        if [[ "${have%% *}" != "$ESPO_VERSION" ]]; then
            die "core ${have%% *} is installed; upgrading to $ESPO_VERSION is not automated yet (docs/local-stand.md)"
        fi
    fi
    local stage src entry
    stage="$(mktemp -d "$CACHE_DIR/stage.XXXXXX")"
    unzip -q "$zip" -d "$stage"
    src="$stage/EspoCRM-$ESPO_VERSION"
    [[ -d "$src/application" ]] || die "unexpected archive layout in $zip"

    local entries=()
    while IFS= read -r entry; do entries+=("$entry"); done < <(cd "$src" && find . -mindepth 1 -maxdepth 1 -printf '%P\n' | sort)
    for entry in "${entries[@]}"; do
        case "$entry" in custom|data) continue ;; esac
        if git -C "$REPO_ROOT" ls-files --error-unmatch -- "$entry" >/dev/null 2>&1 && [[ "$entry" != client ]]; then
            die "core entry '$entry' collides with a file tracked in Git"
        fi
    done

    log "installing EspoCRM $ESPO_VERSION core into $ESPO_ROOT"
    for entry in "${entries[@]}"; do
        case "$entry" in
            custom|data) ;;  # skeletons below; never overwrite customizations or runtime data
            client) rsync -a --delete --exclude=/custom/ "$src/client/" "$ESPO_ROOT/client/" ;;
            *) if [[ -d "$src/$entry" ]]; then rsync -a --delete "$src/$entry/" "$ESPO_ROOT/$entry/"
               else install -m 0644 "$src/$entry" "$ESPO_ROOT/$entry"; fi ;;
        esac
    done
    rsync -a --ignore-existing "$src/custom/" "$ESPO_ROOT/custom/"
    rsync -a --ignore-existing "$src/client/custom/" "$ESPO_ROOT/client/custom/"
    [[ -d "$ESPO_ROOT/data" ]] || install -d -m 0770 "$ESPO_ROOT/data"

    # Core is read-only for everyone but the developer; EspoCRM itself writes only to
    # data/, custom/Espo/{Custom,Modules} and client/custom (see step_perms).
    for entry in "${entries[@]}"; do
        case "$entry" in custom|data) continue ;; esac
        if [[ "$entry" == client ]]; then
            find "$ESPO_ROOT/client" -path "$ESPO_ROOT/client/custom" -prune -o -exec chmod u=rwX,go=rX {} +
        else
            chmod -R u=rwX,go=rX "$ESPO_ROOT/$entry"
        fi
    done
    chmod 0755 "$ESPO_ROOT/bin/command"
    { echo "$want"; printf '%s\n' "${entries[@]}"; } >"$CORE_STAMP"
    rm -rf "$stage"
    log "core $ESPO_VERSION installed (${#entries[@]} top-level entries)"
}

step_perms() {
    [[ -f "$CORE_STAMP" ]] || die "core is not installed (step core)"
    id -u "$ESPO_USER" >/dev/null 2>&1 || die "user $ESPO_USER is missing (step user)"
    # data/: runtime state, config with secrets, uploads — only the web user, no access for others.
    as_root chown -R "$ESPO_USER:$ESPO_USER" "$ESPO_ROOT/data"
    as_root chmod 0770 "$ESPO_ROOT/data"
    as_root chmod -R o-rwx "$ESPO_ROOT/data"
    # Tracked customization directories stay owned by the developer (Git works as usual);
    # the web user gets rw through ACLs, and default ACLs keep new files shared both ways.
    local dir acl="u:$ESPO_USER:rwX,u:$DEV_USER:rwX"
    for dir in custom/Espo/Custom custom/Espo/Modules client/custom; do
        mkdir -p "$ESPO_ROOT/$dir"
        as_root setfacl -R -m "$acl,m::rwX" "$ESPO_ROOT/$dir"
        as_root find "$ESPO_ROOT/$dir" -type d -exec setfacl -d -m "u::rwx,g::r-x,o::r-x,$acl,m::rwx" {} +
    done
    log "permissions applied (data/ -> $ESPO_USER 0770; custom dirs -> ACL for $ESPO_USER and $DEV_USER)"
}

step_mysql() {
    local tarball dir
    tarball="$(fetch_verified "$MYSQL_URL" "$MYSQL_TARBALL" "$MYSQL_SHA256")"
    dir="$MYSQL_OPT/mysql-$MYSQL_VERSION"
    if ! as_root test -x "$dir/bin/mysqld"; then
        as_root install -d -m 0755 "$MYSQL_OPT"
        local tmp
        tmp="$(as_root mktemp -d "$MYSQL_OPT/.extract.XXXXXX")"
        as_root tar -xJf "$tarball" -C "$tmp"
        as_root mv "$tmp/${MYSQL_TARBALL%.tar.xz}" "$dir"
        as_root rmdir "$tmp"
        as_root chown -R root:root "$dir"
        log "MySQL $MYSQL_VERSION unpacked into $dir"
    fi
    local aio
    aio="$(ldconfig -p | awk '$1 ~ /^libaio\.so\.1(t64)?$/ {print $NF; exit}')"
    [[ -n "$aio" ]] || die "libaio is not installed (apt install libaio1t64)"
    as_root install -d -m 0755 "$dir/lib/compat"
    as_root ln -sfn "$aio" "$dir/lib/compat/libaio.so.1"
    as_root ln -sfn "$dir" "$MYSQL_HOME"

    render_to my.cnf.tmpl "$ETC_DIR/my.cnf" 0644
    local changed=$RENDER_CHANGED
    render_to itvolga-espo-mysql.service.tmpl "/etc/systemd/system/$MYSQL_UNIT.service" 0644
    if [[ $RENDER_CHANGED == 1 ]]; then as_root systemctl daemon-reload; changed=1; fi

    if ! as_root test -d "$MYSQL_DATADIR/mysql"; then
        log "initialising $MYSQL_DATADIR (root@localhost -> auth_socket)"
        as_root install -d -m 0750 -o mysql -g mysql "$MYSQL_DATADIR"
        local init
        init="$(as_root mktemp -p "$MYSQL_DATADIR" .init.XXXXXX)"
        printf "INSTALL PLUGIN auth_socket SONAME 'auth_socket.so';\nALTER USER 'root'@'localhost' IDENTIFIED WITH auth_socket;\n" \
            | as_root tee "$init" >/dev/null
        as_root chown mysql:mysql "$init"
        local out rc=0
        out="$(as_user mysql env LD_LIBRARY_PATH="$MYSQL_HOME/lib/compat" "$MYSQL_HOME/bin/mysqld" \
                --defaults-file="$ETC_DIR/my.cnf" --initialize-insecure --init-file="$init" 2>&1)" || rc=$?
        as_root rm -f "$init"
        if [[ $rc -ne 0 ]] || grep -q '\[ERROR\]' <<<"$out"; then
            grep -E '\[(ERROR|Warning)\]' <<<"$out" >&2 || true
            die "MySQL initialisation failed; remove $MYSQL_DATADIR before retrying"
        fi
    fi
    as_root systemctl enable --quiet "$MYSQL_UNIT"
    if unit_active "$MYSQL_UNIT"; then
        [[ $changed == 1 ]] && { log "restarting $MYSQL_UNIT (config changed)"; as_root systemctl restart "$MYSQL_UNIT"; }
    else
        as_root systemctl start "$MYSQL_UNIT"
    fi
    mysql_root -N -e "SELECT CONCAT('MySQL ', @@version, ' on port ', @@port)" | while read -r l; do log "$l"; done

    load_private_env
    [[ "$DB_PASSWORD" =~ ^[A-Za-z0-9]+$ ]] || die "DB_PASSWORD must be alphanumeric"
    mysql_root <<SQL
CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '$DB_USER'@'127.0.0.1' IDENTIFIED BY '$DB_PASSWORD';
ALTER USER '$DB_USER'@'127.0.0.1' IDENTIFIED BY '$DB_PASSWORD';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'127.0.0.1';
SQL
    log "database $DB_NAME and account $DB_USER@127.0.0.1 ready"
}

step_fpm() {
    render_to php-fpm.conf.tmpl "$ETC_DIR/php-fpm.conf" 0644
    local changed=$RENDER_CHANGED
    as_root "$PHP_FPM_BIN" --test --fpm-config "$ETC_DIR/php-fpm.conf" 2>&1 | grep -v 'test is successful' >&2 || true
    render_to itvolga-espo-php-fpm.service.tmpl "/etc/systemd/system/$FPM_UNIT.service" 0644
    if [[ $RENDER_CHANGED == 1 ]]; then as_root systemctl daemon-reload; changed=1; fi
    as_root systemctl enable --quiet "$FPM_UNIT"
    if unit_active "$FPM_UNIT"; then
        [[ $changed == 1 ]] && { log "restarting $FPM_UNIT (config changed)"; as_root systemctl restart "$FPM_UNIT"; }
    else
        as_root systemctl start "$FPM_UNIT"
    fi
    log "PHP-FPM $PHP_VERSION pool listens on $FPM_SOCKET"
}

espo_set_config() { # JSON on stdin
    as_user "$ESPO_USER" "$PHP_BIN" "$STAND_DIR/php/set-config.php" "$ESPO_ROOT"
}

espo_database_json() {
    MYSQL_HOST="$MYSQL_HOST" MYSQL_PORT="$MYSQL_PORT" DB_NAME="$DB_NAME" DB_USER="$DB_USER" DB_PASSWORD="$DB_PASSWORD" \
    python3 -c 'import json, os; e = os.environ; print(json.dumps({"database": {
        "platform": "Mysql", "host": e["MYSQL_HOST"], "port": e["MYSQL_PORT"], "dbname": e["DB_NAME"],
        "user": e["DB_USER"], "password": e["DB_PASSWORD"], "charset": "utf8mb4"}}))'
}

step_espo() {
    load_private_env
    local installed
    installed="$(espo_cmd config:get isInstalled 2>/dev/null || true)"
    if [[ "$installed" != true ]]; then
        log "installing EspoCRM (CLI, same sequence as the official espocrm-docker entrypoint)"
        as_root rm -rf "$ESPO_ROOT/data/cache"
        espo_cmd config:populate
        espo_cmd config:set defaultPermissions.user "$ESPO_USER"
        espo_cmd config:set defaultPermissions.group "$ESPO_USER"
    fi
    # Always re-applied: keeps data/config-internal.php in sync with the private settings
    # (e.g. after a restore of an older backup or a regenerated password).
    espo_database_json | espo_set_config
    [[ "$(espo_cmd db:check 2>&1)" == OK ]] || die "EspoCRM cannot connect to $MYSQL_HOST:$MYSQL_PORT/$DB_NAME"

    if [[ "$installed" != true ]]; then
        espo_cmd rebuild >/dev/null
        espo_cmd create-admin-user "$ESPO_ADMIN_USERNAME" >/dev/null
        printf '%s\n' "$ESPO_ADMIN_PASSWORD" | espo_cmd set-password "$ESPO_ADMIN_USERNAME" >/dev/null 2>&1
        espo_cmd config:set language "$ESPO_LANGUAGE"
        espo_cmd config:set timeZone "$ESPO_TIME_ZONE"
        espo_cmd config:set dateFormat "$ESPO_DATE_FORMAT"
        espo_cmd config:set timeFormat "$ESPO_TIME_FORMAT"
        espo_cmd config:set weekStart "$ESPO_WEEK_START" --type=int
        espo_cmd config:set defaultCurrency "$ESPO_CURRENCY"
        espo_cmd config:set baseCurrency "$ESPO_CURRENCY"
        espo_cmd config:set currencyList "[\"$ESPO_CURRENCY\"]" --type=json
        espo_cmd config:set decimalMark "$ESPO_DECIMAL_MARK"
        espo_cmd config:set thousandSeparator "$ESPO_THOUSAND_SEPARATOR"
        espo_cmd populate-scheduled-jobs >/dev/null
        espo_cmd config:set jobRunInParallel true --type=bool
        # Extensions are never installed from the UI in this project (no paid packages, D-03).
        espo_cmd config:set adminExtensionUpload false --type=bool
    else
        espo_cmd clear-cache >/dev/null
        espo_cmd rebuild >/dev/null
    fi
    espo_cmd config:set siteUrl "$ESPO_SITE_URL"
    espo_cmd app-check >/dev/null || { espo_cmd app-check >&2 || true; die "app-check failed"; }
    if [[ "$installed" != true ]]; then
        espo_cmd config:set isInstalled true --type=bool
        log "EspoCRM $(espo_cmd version) installed; admin user: $ESPO_ADMIN_USERNAME"
    else
        log "EspoCRM $(espo_cmd version) already installed; config, cache and schema refreshed"
    fi
}

step_apache() {
    local mod reload=0
    for mod in rewrite proxy proxy_fcgi setenvif; do
        if [[ ! -e "/etc/apache2/mods-enabled/$mod.load" ]]; then
            as_root a2enmod -q "$mod"; reload=1
        fi
    done
    render_to apache-vhost.conf.tmpl "$APACHE_SITE_FILE" 0644
    [[ $RENDER_CHANGED == 1 ]] && reload=1
    if [[ ! -e "/etc/apache2/sites-enabled/$APACHE_SITE.conf" ]]; then
        as_root a2ensite -q "$APACHE_SITE" >/dev/null; reload=1
    fi
    local out
    out="$(as_root apache2ctl -t 2>&1)" || { printf '%s\n' "$out" >&2; die "apache2ctl -t failed"; }
    if [[ $reload == 1 ]]; then
        log "reloading apache2"
        as_root systemctl reload apache2
    fi
    if ! grep -qE "^[[:space:]]*127\.0\.0\.1[[:space:]]+([^#]*[[:space:]])?${ESPO_SITE_HOST//./\\.}([[:space:]]|$)" /etc/hosts; then
        printf '127.0.0.1\t%s\n' "$ESPO_SITE_HOST" | as_root tee -a /etc/hosts >/dev/null
        log "added $ESPO_SITE_HOST to /etc/hosts"
    fi
    log "vhost $ESPO_SITE_URL -> $ESPO_ROOT/public"
}

step_cron() {
    render_to cron.tmpl "$CRON_FILE" 0644
    log "cron: $CRON_FILE (every minute as $ESPO_USER)"
}

step_health() {
    # Right after a fresh install or restore cron.php may not have run yet.
    wait_cron_run "$(( $(date +%s) - 120 ))" || true
    "$STAND_DIR/health.sh"
}

main() {
    local steps=("$@") step
    [[ ${#steps[@]} -gt 0 ]] || steps=("${ALL_STEPS[@]}")
    for step in "${steps[@]}"; do
        declare -F "step_$step" >/dev/null || die "unknown step '$step' (steps: ${ALL_STEPS[*]})"
    done
    for step in "${steps[@]}"; do
        log "== $step"
        "step_$step"
    done
}

main "$@"
