"""Software security keys for the stand tests: a client of tests/security_key_stand/authenticator.php.

One PHP process per test module holds the key pairs (generated by the run, never written anywhere); each Key is one
registered credential of it. The responses are what a browser sends after the key is touched; options spoil parts of
them (see SoftAuthenticator in tests/security_key/Support).
"""
import base64
import json
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
ES256, EDDSA, RS256 = -7, -8, -257


def b64u(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def unb64u(text: str) -> bytes:
    return base64.urlsafe_b64decode(text + "=" * (-len(text) % 4))


class Authenticators:
    def __init__(self):
        self._process = subprocess.Popen(["php", str(HERE / "authenticator.php")], stdin=subprocess.PIPE,
                                         stdout=subprocess.PIPE, text=True)

    def call(self, **request):
        self._process.stdin.write(json.dumps(request) + "\n")
        self._process.stdin.flush()
        line = self._process.stdout.readline()
        if not line:
            raise RuntimeError("the software authenticator stopped")
        return json.loads(line)

    def key(self, alg=ES256):
        return Key(self, alg)

    def close(self):
        self._process.stdin.close()
        self._process.wait(timeout=10)


class Key:
    def __init__(self, authenticators, alg):
        self._authenticators = authenticators
        answer = authenticators.call(op="new", alg=alg)
        self.handle, self.id = answer["handle"], answer["id"]
        self.counter = 0

    def attest(self, public_key, site, name=None, **o):
        """A registration item as the setup modal sends it, for the creation options of getTwoFactorUserSetupData
        (site — the origin the browser reports; o["origin"] overrides it)."""
        answer = self._authenticators.call(op="attest", handle=self.handle, rpId=public_key["rp"]["id"], origin=site,
                                           challenge=public_key["challenge"], o=o)
        return {"name": name, "id": answer["id"], "clientDataJSON": answer["clientDataJSON"],
                "attestationObject": answer["attestationObject"], "transports": ["usb"]}

    def code(self, public_key, site, sign_count=None, **o):
        """The Espo-Authorization-Code value for the request options of a first login step; counts up by default."""
        if sign_count is None:
            self.counter += 1
            sign_count = self.counter
        return self._authenticators.call(op="assert", handle=self.handle, rpId=public_key["rpId"], origin=site,
                                         challenge=public_key["challenge"], signCount=sign_count, o=o)["code"]
