<?php

declare(strict_types=1);

namespace Itvolga\Tests\SecurityKey\Support;

use Espo\Modules\Itvolga\Tools\SecurityKey\Core\Base64Url;

/**
 * A software authenticator for the tests: a key pair generated by the run (ES256 and RS256 with OpenSSL, EdDSA with
 * sodium; nothing is stored) that builds registration and sign-in responses the way a browser and a security key do,
 * with options to spoil any part of them.
 */
final class SoftAuthenticator
{
    public const ES256 = -7;
    public const EDDSA = -8;
    public const RS256 = -257;

    public readonly string $credentialId;

    /** @var array<int, self> */
    private static array $cache = [];

    private function __construct(
        public readonly int $algorithm,
        private readonly mixed $privateKey,
        private readonly string $coseKey,
    ) {
        $this->credentialId = random_bytes(48);
    }

    /**
     * A fresh authenticator (own credential id) sharing the key pair of its algorithm within the run: RSA key
     * generation is slow.
     */
    public static function create(int $algorithm): self
    {
        $pair = self::$cache[$algorithm] ??= self::generate($algorithm);

        return new self($algorithm, $pair->privateKey, $pair->coseKey);
    }

    public function coseKey(): string
    {
        return $this->coseKey;
    }

    /**
     * @param array<string, mixed> $o type, challenge, origin, crossOrigin, topOrigin, rpId, flags, signCount, fmt,
     *   attStmt (encoded), coseKey (encoded), credentialId, attested (false: no attested credential data), trailing
     *   (bytes after the authenticator data).
     * @return array{clientDataJSON: string, attestationObject: string}
     */
    public function attestation(string $rpId, string $origin, string $challenge, array $o = []): array
    {
        $authenticatorData = $this->authenticatorData($o['rpId'] ?? $rpId, $o['flags'] ?? 0x41, $o['signCount'] ?? 0) .
            (($o['attested'] ?? true) ? $this->attestedCredentialData($o) : '') .
            ($o['trailing'] ?? '');

        return [
            'clientDataJSON' => self::clientData('webauthn.create', $challenge, $origin, $o),
            'attestationObject' => CborWriter::map([
                [CborWriter::text('fmt'), CborWriter::text($o['fmt'] ?? 'none')],
                [CborWriter::text('attStmt'), $o['attStmt'] ?? CborWriter::map([])],
                [CborWriter::text('authData'), CborWriter::bytes($authenticatorData)],
            ]),
        ];
    }

    /**
     * @param array<string, mixed> $o type, challenge, origin, crossOrigin, topOrigin, rpId, flags, trailing,
     *   tamper (flip a signature byte), userHandle, credentialId.
     * @return array{id: string, clientDataJSON: string, authenticatorData: string, signature: string, userHandle: ?string}
     */
    public function assertion(string $rpId, string $origin, string $challenge, int $signCount, array $o = []): array
    {
        $authenticatorData = $this->authenticatorData($o['rpId'] ?? $rpId, $o['flags'] ?? 0x01, $signCount) .
            ($o['trailing'] ?? '');
        $clientData = self::clientData('webauthn.get', $challenge, $origin, $o);
        $signature = $this->sign($authenticatorData . hash('sha256', $clientData, true));

        if ($o['tamper'] ?? false) {
            $signature[10] = chr(ord($signature[10]) ^ 0x01);
        }

        return [
            'id' => $o['credentialId'] ?? $this->credentialId,
            'clientDataJSON' => $clientData,
            'authenticatorData' => $authenticatorData,
            'signature' => $signature,
            'userHandle' => $o['userHandle'] ?? null,
        ];
    }

    /**
     * The value of the Espo-Authorization-Code header the client builds from an assertion.
     *
     * @param array{id: string, clientDataJSON: string, authenticatorData: string, signature: string, userHandle: ?string} $assertion
     */
    public static function code(array $assertion): string
    {
        return Base64Url::encode((string) json_encode([
            'id' => Base64Url::encode($assertion['id']),
            'clientDataJSON' => Base64Url::encode($assertion['clientDataJSON']),
            'authenticatorData' => Base64Url::encode($assertion['authenticatorData']),
            'signature' => Base64Url::encode($assertion['signature']),
            'userHandle' => $assertion['userHandle'] === null ? null : Base64Url::encode($assertion['userHandle']),
        ]));
    }

    /**
     * AAGUID (zeros, as with attestation "none"), credential id length, credential id, COSE key.
     *
     * @param array<string, mixed> $o credentialId, coseKey (encoded).
     */
    public function attestedCredentialData(array $o = []): string
    {
        $credentialId = $o['credentialId'] ?? $this->credentialId;

        return str_repeat("\x00", 16) . pack('n', strlen($credentialId)) . $credentialId . ($o['coseKey'] ?? $this->coseKey);
    }

    private function authenticatorData(string $rpId, int $flags, int $signCount): string
    {
        return hash('sha256', $rpId, true) . chr($flags) . pack('N', $signCount);
    }

    /**
     * @param array<string, mixed> $o
     */
    private static function clientData(string $type, string $challenge, string $origin, array $o): string
    {
        $data = [
            'type' => $o['type'] ?? $type,
            'challenge' => Base64Url::encode($o['challenge'] ?? $challenge),
            'origin' => $o['origin'] ?? $origin,
            'crossOrigin' => $o['crossOrigin'] ?? false,
            // Chrome adds this member to make sure servers parse the JSON rather than compare it with a template.
            'other_keys_can_be_added_here' => 'do not compare clientDataJSON against a template',
        ];

        if (array_key_exists('topOrigin', $o)) {
            $data['topOrigin'] = $o['topOrigin'];
        }

        return (string) json_encode($data, JSON_UNESCAPED_SLASHES);
    }

    private function sign(string $data): string
    {
        if ($this->algorithm === self::EDDSA) {
            return sodium_crypto_sign_detached($data, $this->privateKey);
        }

        openssl_sign($data, $signature, $this->privateKey, OPENSSL_ALGO_SHA256);

        return $signature;
    }

    private static function generate(int $algorithm): self
    {
        if ($algorithm === self::EDDSA) {
            $pair = sodium_crypto_sign_keypair();

            return new self($algorithm, sodium_crypto_sign_secretkey($pair), CborWriter::map([
                [CborWriter::int(1), CborWriter::int(1)],
                [CborWriter::int(3), CborWriter::int(self::EDDSA)],
                [CborWriter::int(-1), CborWriter::int(6)],
                [CborWriter::int(-2), CborWriter::bytes(sodium_crypto_sign_publickey($pair))],
            ]));
        }

        $key = $algorithm === self::ES256 ?
            openssl_pkey_new(['private_key_type' => OPENSSL_KEYTYPE_EC, 'curve_name' => 'prime256v1']) :
            openssl_pkey_new(['private_key_type' => OPENSSL_KEYTYPE_RSA, 'private_key_bits' => 2048]);
        $details = openssl_pkey_get_details($key);

        if ($algorithm === self::ES256) {
            return new self($algorithm, $key, CborWriter::map([
                [CborWriter::int(1), CborWriter::int(2)],
                [CborWriter::int(3), CborWriter::int(self::ES256)],
                [CborWriter::int(-1), CborWriter::int(1)],
                [CborWriter::int(-2), CborWriter::bytes(str_pad($details['ec']['x'], 32, "\x00", STR_PAD_LEFT))],
                [CborWriter::int(-3), CborWriter::bytes(str_pad($details['ec']['y'], 32, "\x00", STR_PAD_LEFT))],
            ]));
        }

        return new self($algorithm, $key, CborWriter::map([
            [CborWriter::int(1), CborWriter::int(3)],
            [CborWriter::int(3), CborWriter::int(self::RS256)],
            [CborWriter::int(-1), CborWriter::bytes($details['rsa']['n'])],
            [CborWriter::int(-2), CborWriter::bytes($details['rsa']['e'])],
        ]));
    }
}
